dist: trusty
sudo: false
group: beta

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=py35
    - python: 2.7
      env: TOXENV=style
    - python: 2.7
      env: TOXENV=readme

install: pip install tox

script: tox

branches:
  only:
    - master

notifications:
  email: false
